#ARG tag=latest
FROM ngiccorddemo/ngic-builder:latest 

ENV NG_CORE /opt/ng-core
COPY . ${NG_CORE}
WORKDIR ${NG_CORE}

RUN apt-get update && apt-get -y install  libssl-dev

RUN make clean && make -j4 build-lib && \
    make -j4 build-dp EXTRA_CFLAGS="-DSTATS -DOSTATS"


RUN mkdir /opt/ngic
RUN mkdir /opt/ngic/bin
RUN cp /opt/ng-core/dp/build/ngic_dataplane /opt/ngic/bin/ngic_dataplane

# 20 CP/DP Comm
EXPOSE 20/UDP

# Mount the config folder here at runtime
VOLUME /opt/ngic/config

WORKDIR /opt/ngic/bin

CMD . /opt/ngic/config/dp_config.cfg && ifconfig -a && \
    ./ngic_dataplane $EAL_ARGS -- $APP_ARGS
