FROM ngiccorddemo/ngic-builder:latest  

ENV NG_CORE /opt/ng-core
COPY . ${NG_CORE}
WORKDIR ${NG_CORE}

RUN make clean && make -j4 build-cp


#RUN ls cp/build/  -la
RUN mkdir /opt/ngic
RUN mkdir /opt/ngic/bin
RUN cp cp/build/ngic_controlplane /opt/ngic/bin/ngic_controlplane

# 2123 GTP-Control
EXPOSE 2123/UDP

# Mount the config folder here at runtime
VOLUME /opt/ngic/config

WORKDIR /opt/ngic/bin

CMD . /opt/ngic/config/cp_config.cfg && ifconfig -a && \
    ./ngic_controlplane $EAL_ARGS -- $APP_ARGS
