FROM ubuntu:16.04 as ngic-builder

RUN apt-get update && apt-get -y install build-essential wget \
    libboost-all-dev cmake ragel \
    libzmq3-dev libcurl4-openssl-dev  \
    libpcap0.8-dev libjson0-dev


ENV RTE_SDK /opt/dpdk
ENV RTE_TARGET arm64-armv8a-linuxapp-gcc

COPY dpdk ${RTE_SDK}
COPY dpdk-16.04_common_linuxapp ${RTE_SDK}/config/common_linuxapp
WORKDIR ${RTE_SDK}
RUN sed -ri 's,(IGB_UIO=).*,\1n,' config/common_linuxapp && \
    sed -ri 's,(KNI_KMOD=).*,\1n,' config/common_linuxapp && \
    make -j4 install T=${RTE_TARGET}
